version: "1.0"
info:
  model: int-scaffold
packages:
- name: LogisticsProject
  gitServerName: AvivSimDSLogistics
  gitUrl: https://github.com/AvivSimDS/LogisticsProject
  gitUsername: AvivSimDS
  gitBranch: main
